[InputMethod]
Name=Sekka
Icon=snowflake
Label=雪
LangCode=zh_HK
Addon=table
Configurable=True

[Table]
File=table/sekka.main.dict
OrderPolicy=Freq
AutoSelect=True
AutoSelectLength=5
NoMatchAutoSelectLength=4
MatchingKey=*
ExactMatch=True
Hint=False
IgnorePunc=True

[Table/PrevCandidate]
0=Left
1=,

[Table/NextCandidate]
0=Right
1=.

[Table/PrevPage]
0=Up
1=lower
2=minus

[Table/NextPage]
0=Down
1=greater
2=equal
